typography_spectrum: 0.5594996
content_rating:
  adult: false
color:
  lightness: 0.8290995
  brandStrength: 0.6283711
  saturation: 0.9780253
  rhythmicContrast: 0.424864
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
github: true
layout_spectrum: 0.3527244
author:
  name: 'Chica IO '
  email: vanessa@chica.io
  url: 'http://issues.chica.io'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2c81a7e7-c24a-470f-972f-35011fe83e7e.png
name: Issues
url: 'http://issues.chica.io/'
navigation:
  - name: Home
    url: 'http://chica.io'
    type: external
  - name: News
    url: 'http://news.chica.io'
    type: external
  - name: Issues
    url: 'http://issues.chica.io'
    type: external
  - name: Policy
    url: 'http://issues.chica.io/policy'
    type: external
  - name: Fearless Girl
    id: efcdba94-a7a1-4bc2-9176-6377dd51e4e8
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b3e9990f-0e12-446c-ba28-a8de78085e3c.jpg
title: CHICA
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/443ee84b-914e-469b-9ed2-b766b587c7ec.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/443ee84b-914e-469b-9ed2-b766b587c7ec.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ba52f148-b2ac-487b-8666-e3f623b3896e.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ba52f148-b2ac-487b-8666-e3f623b3896e.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: News | Issues | Policy
