layout_spectrum: 0.3527244
typography_spectrum: 0.5594996
color:
  lightness: 0.8290995
  brandStrength: 0.6283711
  saturation: 0.9780253
  rhythmicContrast: 0.424864
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: 'WoC '
content: []
github: true
author:
  name: Vanessa Smith
  email: vanessa@chica.io
  url: 'https://news.chica.io'
url: 'https://news.chica.io'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2c81a7e7-c24a-470f-972f-35011fe83e7e.png
content_rating:
  adult: false
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b3e9990f-0e12-446c-ba28-a8de78085e3c.jpg
